### ISSUE TITLE
[BUG]鉴权失败后会给出000UUID并使玩家成功进服

### ISSUE THREAD

**Issue by KelaLeaf** [YggdrasilGateway/YggdrasilGateway#2]
我目前的设置
![5D6895A571929C45B3A80CBC4BA33407](https://github.com/user-attachments/assets/238dfc70-b585-4f51-a710-de7ffda00c41)
玩家进服报错：
![C3EA4C75DCEB357D8E89D54707B6C0C2](https://github.com/user-attachments/assets/c8382a29-aaf8-4208-af3b-3ba873b58e5a)
服务器获取到000uiid并使玩家加入服务器
![24C947FAEF163530535933FBDCA509C0](https://github.com/user-attachments/assets/742ef6f1-6fca-49a8-8a74-5cd273549753)

**Comment by Karlatemp** [comment]
在 Velocity 安装 https://github.com/YggdrasilGateway/GatewayEnhancement 或者 关闭增强拒绝模式

**Comment by KelaLeaf** [comment]
> 在 Velocity 安装 https://github.com/YggdrasilGateway/GatewayEnhancement 或者 关闭增强拒绝模式

我是fabric纯mod服，添加插件会导致大量mod不兼容，所以没有启用插件功能，看来只有关闭增强拒绝模式了，会考虑出mod吗？

**Comment by Karlatemp** [comment]
暂时不会考虑，精力不足以维护多个平台与版本
